name: etraffic_app
description: A new Flutter project.
version: 1.0.0+1

# Add this environment block right here:
environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.1